#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright (c) 2025 David Kristiansen

# bundle.sh — assemble a single self-contained stow.sh executable.
#
# Concatenates every sourced module and built-in condition plugin into one
# file so users can download a single script, chmod +x, and run it — no
# extraction, no PREFIX, no conditions.d directory needed. User condition
# overrides in $XDG_CONFIG_HOME/stow.sh/conditions still load at runtime.
#
# Usage: scripts/bundle.sh [output-path]
#   output-path — where to write the bundle (default: dist/stow.sh)

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${1:-$ROOT/dist/stow.sh}"

# Module load order mirrors the source block in src/main.sh: every function
# must be defined before main.sh's logic (appended last) calls it.
MODULES=(version log args conditions filter scan fold xdg dotfiles stow)

VERSION="$(sed -n 's/^STOW_SH_VERSION="\(.*\)"/\1/p' "$ROOT/src/version.sh")"

mkdir -p "$(dirname "$OUT")"

{
    printf '#!/usr/bin/env bash\n'
    printf '# stow.sh %s — single-file bundle.\n' "$VERSION"
    printf '# Generated by scripts/bundle.sh — DO NOT EDIT. Edit src/ and rebuild.\n'
    printf '# SPDX-License-Identifier: MIT\n'
    printf 'set -euo pipefail\n\n'

    for m in "${MODULES[@]}"; do
        printf '# ===== src/%s.sh =====\n' "$m"
        cat "$ROOT/src/$m.sh"
        printf '\n'
    done

    # Built-in condition plugins, inlined as plain function definitions.
    # load_condition_plugins() still runs at startup to pick up user overrides
    # from XDG_CONFIG_HOME; missing built-in dirs are handled gracefully.
    for f in "$ROOT"/conditions.d/*.sh; do
        printf '# ===== conditions.d/%s =====\n' "$(basename "$f")"
        cat "$f"
        printf '\n'
    done

    # src/main.sh logic, minus the preamble that only makes sense for the
    # multi-file layout: the shebang, the STOW_ROOT discovery, and the
    # `source` lines (all modules are already inlined above).
    printf '# ===== src/main.sh =====\n'
    # The '$ROOT' in the sed pattern is a literal to match in main.sh, not a
    # variable to expand — single quotes are intentional.
    # shellcheck disable=SC2016
    sed -E \
        -e '/^#!/d' \
        -e '/^ROOT=/d' \
        -e '/^export STOW_ROOT=/d' \
        -e '/^source "\$ROOT\/src\//d' \
        "$ROOT/src/main.sh"
} > "$OUT"

chmod +x "$OUT"
echo "Bundled stow.sh $VERSION → $OUT"
